// File: app/src/main/java/com/rushdululilm/app/data/local/SavedAnswer.kt
// Purpose: Defines the table structure for saving fatwa answers in the local database
// Layer: Layer 1 — Android App (Data Layer)
// Depends on: Room library
// Created: 2026-06-12 | Modified: 2026-06-12
// Developer: Shaik Hidayatullah

/*
 * WHAT IS A ROOM ENTITY?
 * In Android, a Room Entity is simply a blueprint that tells the local database how to create a table.
 * 
 * REAL-LIFE ANALOGY:
 * Think of it like a printed form for a library card. The form has specific blank boxes for "Name", "Date", and "Book Title".
 * When we fill out the form, it becomes a row in our database. The @Entity tag tells Android, "Make a spreadsheet using these boxes as column headers."
 * 
 * 📁 File Placement:
 * Goes in: app/src/main/java/com/rushdululilm/app/data/local/
 * Why here: The 'data/local' folder is dedicated to offline storage mechanisms like SQLite databases.
 * Relates to: SavedAnswerDao.kt (which writes these forms) and RushdulIlmDatabase.kt (which holds the whole spreadsheet).
 */

package com.rushdululilm.app.data.local
// ^ Defines the package where this file lives, matching our folder structure

import androidx.room.Entity
// ^ Imports the Room annotation to mark this class as a database table
import androidx.room.PrimaryKey
// ^ Imports the annotation that designates the unique ID column

@Entity(tableName = "saved_answers")
// ^ Tells Room to create a SQLite table named 'saved_answers' based on the class below
data class SavedAnswer(
// ^ A 'data class' in Kotlin automatically provides helpful functions for storing data
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    // ^ '@PrimaryKey(autoGenerate = true)' means Room will automatically assign a unique number (1, 2, 3) to each new answer
    val questionText: String,
    // ^ Stores the exact text of the user's original question
    val answerText: String,
    // ^ Stores the complete text of the fatwa answer generated by the system
    val sourcesJson: String,
    // ^ Stores the list of citation URLs. Since Room can't store a 'List' directly, we convert it to a JSON text string first
    val language: String,
    // ^ Stores the language of the answer (e.g., "Telugu", "Urdu", "English")
    val savedAtTimestamp: Long,
    // ^ Stores the exact date and time the answer was saved, measured in milliseconds since 1970
    val isOfflineCache: Boolean
    // ^ Stores true if the answer was generated fully offline, false if it came from the live server
)
// ^ Closes the data class body
